# Generated by Django 5.2.10 on 2026-01-26 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('consent', models.BooleanField(verbose_name='Присутвие')),
                ('alcohol', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('wine_red', 'Красное вино'), ('wine_white', 'Белое вино'), ('champagne', 'Шампанское'), ('vodka', 'Водка'), ('cognac', 'Коньяк')], max_length=20), blank=True, default=list, size=None, verbose_name='Предпочитаемый алкоголь')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'db_table': 'guest',
                'ordering': ['first_name'],
            },
        ),
    ]
