# Generated by Django 5.2.10 on 2026-06-25 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_invation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='alcohol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Красное вино', 'Красное вино'), ('Белое вино', 'Белое вино'), ('Шампанское', 'Шампанское'), ('Водка', 'Водка'), ('Коньяк', 'Коньяк')], max_length=20), blank=True, default=list, size=None, verbose_name='Предпочитаемый алкоголь'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='consent',
            field=models.BooleanField(verbose_name='Подтвердите свое присутвие'),
        ),
    ]
